# Generated by Django 3.2.9 on 2021-11-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='mobile',
            field=models.BigIntegerField(),
        ),
    ]
